In [24]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Compras.csv', sep=';')
display(df.head())

,CódigoCompra,Data,Fornecedor,Produto,Quantidade,ValorUnitário,ValorFinal
0,65014,01/12/2023,Fabrica Hashtag Brasil,Óleo Motor - Linha A,5,259.0,1295.0
1,65014,01/12/2023,Fabrica Hashtag Brasil,Kit Embreagem - Linha A,1,380.0,380.0
2,65016,01/12/2023,Fabrica Doidona Brasil,Bateria - Linha A,2,479.0,958.0
3,65016,01/12/2023,Fabrica Doidona Brasil,Filtro de Óleo - Linha A,1,18.9,18.9
4,65017,01/12/2023,Original Fábrica Brasil,Farol Principal - Linha A,3,159.9,479.7

In [25]:
for colunas in df.columns:
    print(colunas)

CódigoCompra
Data
Fornecedor
Produto
Quantidade
ValorUnitário
ValorFinal

In [26]:
# Qual o produto mais vendido?
maisVendido = round(df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False).head(1))
print(maisVendido)

Produto
Filtro Combustível - Linha Premium    163
Name: Quantidade, dtype: int64

In [27]:
# Relacione as vendas por fornecedor.
vendForn = df.groupby('Fornecedor')['ValorUnitário'].sum().sort_index()
print(vendForn)

Fornecedor
Fabrica Doidona Argentina         84310.71
Fabrica Doidona Asia             178888.33
Fabrica Doidona Brasil           190331.49
Fabrica Doidona EUA              100584.30
Fabrica Doidona Europa           136624.59
Fabrica Doidona Mexico           127354.94
Fabrica Hashtag Argentina        135777.43
Fabrica Hashtag Asia             116411.42
Fabrica Hashtag Brasil           124455.85
Fabrica Hashtag EUA              152837.27
Fabrica Hashtag Europa           146372.12
Fabrica Hashtag Internacional    130867.18
Fabrica Hashtag Mexico           182857.53
Original Fábrica Argentina       115564.92
Original Fábrica Asia            154499.26
Original Fábrica Brasil          128559.98
Original Fábrica EUA             148580.59
Original Fábrica Europa          144674.60
Original Fábrica Mexico          113321.55
Revenda Argentina                151150.10
Revenda Asia                      97718.20
Revenda Brasil                   136393.89
Revenda EUA                      191403.92
Revenda Europa                   110812.80
Revenda Mexico                   153063.33
Name: ValorUnitário, dtype: float64

In [28]:
# Data que os produtos foram mais vendidos.
data = round(df.groupby('Data')['Quantidade'].sum().sort_values(ascending=False).head(1))
print(data)

Data
01/12/2023    485
Name: Quantidade, dtype: int64

In [30]:
df['Regiao'] = df['Fornecedor'].str.split().str[-1]
display(df.head(20))

,CódigoCompra,Data,Fornecedor,Produto,Quantidade,ValorUnitário,ValorFinal,Regiao
0,65014,01/12/2023,Fabrica Hashtag Brasil,Óleo Motor - Linha A,5,259.00,1295.00,Brasil
1,65014,01/12/2023,Fabrica Hashtag Brasil,Kit Embreagem - Linha A,1,380.00,380.00,Brasil
2,65016,01/12/2023,Fabrica Doidona Brasil,Bateria - Linha A,2,479.00,958.00,Brasil
3,65016,01/12/2023,Fabrica Doidona Brasil,Filtro de Óleo - Linha A,1,18.90,18.90,Brasil
4,65017,01/12/2023,Original Fábrica Brasil,Farol Principal - Linha A,3,159.90,479.70,Brasil
5,65018,01/12/2023,Revenda Brasil,Radiador - Linha A,1,256.90,256.90,Brasil
6,65018,01/12/2023,Revenda Brasil,Filtro Combustível - Linha A,1,183.34,183.34,Brasil
7,65018,01/12/2023,Revenda Brasil,Kit Embreagem - Linha A,1,380.00,380.00,Brasil
8,65019,01/12/2023,Fabrica Hashtag Europa,Mola de pressão - Linha A,2,39.62,79.24,Europa
9,65019,01/12/2023,Fabrica Hashtag Europa,Rolamento das Rodas - Linha A,1,187.90,187.90,Europa
10,65020,01/12/2023,Fabrica Hashtag Brasil,Correia - Linha A,4,119.92,479.68,Brasil
11,65020,01/12/2023,Fabrica Hashtag Brasil,Bomba d'agua - Linha A,5,553.90,2769.50,Brasil
12,65020,01/12/2023,Fabrica Hashtag Brasil,Pneus - Linha A,2,359.91,719.82,Brasil
13,65024,01/12/2023,Fabrica Doidona Europa,Condensador - Linha A,2,689.90,1379.80,Europa
14,65025,01/12/2023,Original Fábrica Europa,Barra Estabilizadora - Linha A,5,395.80,1979.00,Europa
15,65025,01/12/2023,Original Fábrica Europa,Logo Hashtag - Linha A,1,10.00,10.00,Europa
16,65025,01/12/2023,Original Fábrica Europa,Terminal de Direção - Linha A,1,136.00,136.00,Europa
17,65027,01/12/2023,Revenda Europa,Foto do Lira - Linha A,1,870.00,870.00,Europa
18,65028,01/12/2023,Fabrica Doidona Brasil,Volante - Linha A,5,530.00,2650.00,Brasil
19,65028,01/12/2023,Fabrica Doidona Brasil,Caixa de Marcha - Linha A,1,4990.00,4990.00,Brasil

In [31]:
top5_produtos = df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False).head(5)
print(top5_produtos)

Produto
Filtro Combustível - Linha Premium    163
Bomba d'agua - Linha A                159
Filtro Combustível - Linha B          158
Correia - Linha A                     157
Terminal de Direção - Linha C         157
Name: Quantidade, dtype: int64

In [32]:
maisCaro = df.loc[df['ValorFinal'].idxmax()]
print(maisCaro)

CódigoCompra                               65793
Data                                  05/12/2023
Fornecedor                Fabrica Hashtag Europa
Produto          Caixa de Marcha - Linha Premium
Quantidade                                     5
ValorUnitário                           11218.77
ValorFinal                              56093.84
Regiao                                    Europa
Name: 782, dtype: object

In [33]:
top1Fornecedor = df.groupby('Fornecedor')['Quantidade'].sum().idxmax()
print(f'O fornecedor que mais vendeu foi {top1Fornecedor}')

O fornecedor que mais vendeu foi Revenda EUA

In [34]:
df['Data'] = pd.to_datetime(df['Data'], format='%d/%m/%Y')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4543 entries, 0 to 4542
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CódigoCompra   4543 non-null   int64
 1   Data           4543 non-null   datetime64[us]
 2   Fornecedor     4543 non-null   str
 3   Produto        4543 non-null   str
 4   Quantidade     4543 non-null   int64
 5   ValorUnitário  4543 non-null   float64
 6   ValorFinal     4543 non-null   float64
 7   Regiao         4543 non-null   object
dtypes: datetime64[us](1), float64(2), int64(2), object(1), str(2)
memory usage: 284.1+ KB
None

In [35]:
faturamento_total = df['ValorFinal'].sum()
print(f'Faturamento total: R$ {faturamento_total:.2f} reais')

Faturamento total: R$ 7254196.58 reais